### ISSUE TITLE
CSC : warning CS8032: An instance of analyzer SecurityCodeScan.Analyzers.AthorizationAttributeDiagnosticAnalyzer cannot be created from ...

### ISSUE THREAD

**Issue by jmservera** [security-code-scan/security-code-scan-add-action#2]
Hi, I was trying to use the action with a .net 4.5.2 application but the analyzer didn't run and I found lots of CS8032 warnings. The cause seems to be a dependency on the YamlDotNet.dll that is not added in the analyzers list as it is added when you add the analyzer from Visual Studio.

I fixed it [in my repo](https://github.com/jmservera/LongRunningApi/blob/d33cae7961190a12821c1d935564d2f873b252e4/.github/workflows/securitycodescan-analysis.yml) by adding a new block like this

```ps1
$analyzer = $project.CreateElement('Analyzer', $project.Project.NamespaceURI)
$analyzerInclude = $project.CreateAttribute('Include')
$analyzerInclude.Value = Join-Path -Path $SecurityCodeScanPackagePath -ChildPath "$($SecurityCodeScanPackageName).$($SecurityCodeScanPackageVersion)\analyzers\dotnet\YamlDotNet.dll"
$analyzer.Attributes.Append($analyzerInclude) | Out-Null
$itemGroup.AppendChild($analyzer) | Out-Null
```
I will create a PR to fix this

**Comment by JarLob** [comment]
Fixed in 5f75674efc0abc4d41aa8cf3f1706ed5fe9365dd
